spring.datasource.url: jdbc:mysql://localhost:3306/blog?serverTimezone=Europe/Moscow&createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username: root
spring.datasource.password: test
spring.jpa.database-platform: org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto: none

spring.jpa.show-sql: true
# инициализация базы данных из файлов .sql
spring.datasource.initialization-mode: always
spring.datasource.schema: classpath:database-init/schema.sql
spring.datasource.data: classpath:database-init/TestData.sql

# время хранения капч в БД
captcha.duration: 1h

# настройки для загрузки картинок
upload.dir: src/main/resources/upload/
upload.image-max-size: 5 #(MB)

spring.servlet.multipart.max-request-size: 20MB    # максимальный общий размер любого запроса (default 10MB)
spring.servlet.multipart.max-file-size: 10MB    # максимальный размер любого файла в запросе (default 1MB)

